[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"
authors = ["boris.lok <boris.lok.tw@outlook.com>"]

[lib]
path = "src/lib.rs"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
regex = "1.7.0"

[dev-dependencies]
rand = "0.8.5"
